name: Generate Git Tag
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Generate Git Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          echo "::set-output name=latest_tag::$(git describe --tags --abbrev=0)"
      - name: Generate new tag
        id: generate_tag
        run: |
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR=$(echo "${{ steps.get_latest_tag.outputs.latest_tag }}" | sed 's/^v//')
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | tail -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi
          NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      - name: Push new tag
        if: steps.generate_tag.outputs.NEW_TAG != ''
        run: |
          git tag ${{ steps.generate_tag.outputs.NEW_TAG }}
          git push origin ${{ steps.generate_tag.outputs.NEW_TAG }}
