name: Generate Git Tag
on:
  push:
    branches:
      - main
permissions: 
  write-all
jobs:
  build:
    name: Generate Git Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Generate new tag
        id: generate_tag
        run: |
          VERSION_PREFIX="v"
          echo $VERSION_PREFIX

          VERSION_MAJOR_MINOR=$(echo "${{ env.latest_tag }}" | sed 's/^v//')
          echo $VERSION_MAJOR_MINOR
          NEW_TAG=$((VERSION_MAJOR_MINOR + 1))
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$VERSION_PREFIX$NEW_TAG" >> $GITHUB_ENV

      - name: Push new tag
        if: ${{env.NEW_TAG != ''}}
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
