name: Increment Version Tag

on:
  push:
    branches: [ main ]  # Change this to your desired branch(es)

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest tag
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "Latest tag: $VERSION"

      # Extract major, minor, and patch version (assuming semantic versioning)
      - name: Extract version components
        run: |
          MAJOR=$(echo "$VERSION" | cut -d'.' -f1)
          MINOR=$(echo "$VERSION" | cut -d'.' -f2)
          PATCH=$(echo "$VERSION" | cut -d'.' -f3)
          echo "Major: $MAJOR, Minor: $MINOR, Patch: $PATCH"

      # Increment patch version by default
      - name: Increment patch version
        run: |
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "New version: $NEW_VERSION"

      # Optionally, customize increment logic (e.g., for major/minor increments)
      # - name: Customize increment logic (optional)
      #   run: |
      #     # Implement your custom logic here to modify NEW_VERSION based on tags or other factors

      - name: Create new tag
        run: git tag -a "$NEW_VERSION" -m "New version $NEW_VERSION"

      - name: Push tags
        run: git push origin --tags