name: Clone And Push to Deploy Resource

on:
 workflow_dispatch: 
#  pull_request: 
#   types: 
#     - opened

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{github.head_ref}} #main  # Specify the branch you want to clone

    - name: Set up Git
      run: |
        git config user.name "rajeshr7"
        git config user.email "rajesh.r11@kyndryl.com"

    - name: Get 
      run: |
        echo 'Target Branch ${{github.base_ref}}'
        echo 'Head Branch ${{github.head_ref}}'

    - name: Clone repository
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        git clone --branch ${{github.head_ref}} "https://github.com/${{ github.repository }}" cloned-repo

    - name: Set up Git for Enterprise
      run: |
        cd cloned-repo
        pwd
        ls
        mkdir client
        mv iac client                          
        git remote add enterprise "https://rajeshr7:${{secrets.KYN_GIT_PAT }}@github.kyndryl.net/cloud-practice-engineering/az-terraform-iac.git"

    - name: Push to Enterprise repository
      env:
        GITHUB_TOKEN: ${{ secrets.KYN_GIT_PAT }}    
      run: |
        cd cloned-repo       
        # #git push -u enterprise -f
        git config user.name "rajeshr7"
        git config user.email "rajesh.r11@kyndryl.com"
        git add temp
        git commit -m "iac folder updated"
        git push enterprise ${{github.head_ref}}:Dev -f