name: Pull Request Close and Cancel

on: 
  repository_dispatch:
    types: [PR_CLOSE_CANCEL]

jobs:
  PR_CLOSE_CANCEL:
    runs-on: ubuntu-latest
    env:
      PRNUMBER:  ${{ github.event.client_payload.PRNUMBER }}
      ACTION: ${{ github.event.client_payload.ACTION }}
      COMMENTS:  ${{ github.event.client_payload.COMMENTS }}
    permissions: 
      write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Close PR
      if: ${{env.ACTION == 'CLOSE' }}
      run: |
       echo "Closing PR: ${{env.PRNUMBER}} with Comment: ${{env.COMMENTS}}"
       curl -X POST \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d "{\"body\": \"${{ env.COMMENTS }}\"}" \
           "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PRNUMBER }}/comments"

        # Merge the PR to the main branch using the GitHub REST API
       curl -X PUT \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           "https://api.github.com/repos/${{ github.REPOSITORY }}/pulls/${{ env.PR_NUMBER }}/merge"

        # Close the PR using the GitHub REST API
       curl -X PATCH \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d '{"state": "closed"}' \
           "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PRNUMBER }}"

    - name: Cancel PR
      if: ${{env.ACTION == 'CANCEL'}}
      run: |        
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"body\": \"${{ env.COMMENTS }}\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PRNUMBER }}/comments"

        # Close the PR using the GitHub REST API
        curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"state": "closed"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PRNUMBER }}"
